//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AnimateBuilder.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_AnimateBuilderCsc_          101
#define IDR_AnimateBuilderJsc_          102
#define IDR_AnimateBuilder_Ana          103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_AnimateBuilderAda           105
#define IDR_AnimateBuilder_Arena        106
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_AnimateBuilderTYPE          130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_FILENEWDIALOG               310
#define IDD_DIALOG1                     311
#define IDD_DIALOG2                     313
#define IDD_DIALOG3                     316
#define IDD_DIALOG4                     318
#define IDD_DIALOG5                     320
#define IDC_RADIO1                      1000
#define IDC_RADIO2                      1001
#define IDC_RADIO3                      1002
#define IDC_RADIO4                      1003
#define IDC_RADIO5                      1004
#define IDC_RADIO6                      1005
#define IDC_RADIO7                      1006
#define IDC_COMBO1                      1007
#define IDC_COMBO2                      1008
#define IDC_CHECK1                      1009
#define IDC_RADIO8                      1010
#define IDC_RADIO9                      1011
#define IDC_RADIO10                     1012
#define IDC_RADIO11                     1013
#define IDC_RADIO12                     1014
#define IDC_RADIO13                     1015
#define IDC_EDIT1                       1016
#define IDC_EDIT2                       1017
#define IDC_BUTTON1                     1018
#define IDC_CHECK4                      1025
#define IDC_CHECK5                      1026
#define IDC_MFCCOLORBUTTON1             1027
#define IDC_MFCCOLORBUTTON2             1028
#define IDC_COMBO3                      1029
#define IDC_COMBO4                      1030
#define IDC_COMBO5                      1031
#define IDC_BUTTON2                     1033
#define IDC_CHECK6                      1034
#define IDC_MFCCOLORBUTTON3             1035
#define IDC_COMBO7                      1036
#define IDC_COMBO8                      1037
#define IDC_COMBO9                      1038
#define IDC_COMBO10                     1039
#define IDC_BUTTON3                     1040
#define IDC_EDIT3                       1041
#define IDC_EDIT4                       1042
#define IDC_EDIT5                       1043
#define IDC_EDIT6                       1044
#define IDC_EDIT7                       1045
#define IDC_CHECK7                      1046
#define IDC_CHECK8                      1047
#define IDC_EDIT8                       1048
#define IDC_EDIT9                       1049
#define IDC_EDIT10                      1050
#define IDC_EDIT11                      1051
#define IDC_COMBO11                     1053
#define IDC_CHECK2                      1054
#define IDC_CHECK3                      1055
#define IDC_CHECK9                      1056
#define IDC_EDIT12                      1057
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_CONTEXT2                     32771
#define ID_CONTEXT3                     32772
#define ID_CONTEXT4                     32773
#define ID_CONTEXT5                     32774
#define ID_BUTTON2                      32775
#define ID_BUTTON3                      32776
#define ID_COMBO2                       32777
#define ID_BUTTON4                      32778
#define ID_BUTTON5                      32779
#define ID_COMBO3                       32780
#define ID_BUTTON6                      32782
#define ID_BUTTON7                      32783
#define ID_BUTTON10                     32786
#define ID_BUTTON12                     32788
#define ID_BUTTON8                      32789
#define ID_BUTTON9                      32790
#define ID_BUTTON11                     32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        322
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
